simple:
  cluster_type: basic
  template: cluster-basic.yml.j2

  head:
    hostname: 'head'
    image: 'centos:7.7.1908-ssh'

  compute:
    hostname:
        prefix: 'node'
        suffix_len: 3          
    image:  'centos:7.7.1908-ssh'
