simple:
  cluster_type: default
  template: cluster-default.yml.j2

  head:
    hostname: 'head'
    image: 'centos:7.7.1908'

  compute:
    hostname:
        prefix: 'node'
        suffix_len: 3          
    image:  'centos:7.7.1908'
