---

- hosts: all
  gather_facts: false
  user: root
  tasks:

    - name: (ansible) Install ansible on head
      yum:
        name: ansible
        state: present
      when: "'head' in group_names"

    - name: (ansible) Copy our inventory to head
      copy:
        src: "{{ dansible.inventory_basepath }}/{{ cluster_name }}/{{ dansible.inventory_filename }}"
        dest: /etc/ansible/hosts
      when: "'head' in group_names"

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    dansible:
      inventory_basepath: ../../clusters
      inventory_filename: inventory.yml
