---

networking:
    supernet: '172.30.0.0/16'
    cidr_bits: 24
    prefix: 'dcluster'
    gateway: 'gateway'

paths:
  ssh_public_keys:
    - $HOME/.ssh/id_rsa.pub

prefs:
  ssh_user: 'root'
  inject_ssh_public_keys_to_root: True
