---

networking:
    supernet: '172.30.0.0/16'
    cidr_bits: 24
    prefix: 'dcluster'
    gateway: 'gateway'

paths:
  ssh_public_key: $HOME/.ssh/id_rsa.pub

prefs:
  ssh_user: 'root'
  inject_ssh_public_key_to_root: True

clusters:
  
  simple:

    cluster_type: basic
    template: cluster-basic.yml.j2

    head:
      hostname: 'head'
      image: 'centos7:ssh'

    compute:
      hostname:
          prefix: 'node'
          suffix_len: 3          
      image:  'centos7:ssh'

  build:
    extend: simple
    template: cluster-basic.yml.j2

    head:
      image: 'centos7:build'

    compute:
      image: 'centos7:build'
  
  slurm:
    
    cluster_type: extended
    compute:
      docker_volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      image: rhel76-slurm:v2
      shared_volumes:
      - /home:/home
      - /opt/intel:/opt/intel
      - /srv/shared:/srv/dcluster/shared
      static:
        command:
        - 'slurmd'
        expose:
        - '6818'
        shm_size: 4g
    extend: simple
    
    head:
      docker_volumes:
      - var_lib_mysql:/var/lib/mysql
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      image: rhel76-slurm:v2
      shared_volumes:
      - /home:/home
      - /opt/intel:/opt/intel
      - /srv/shared:/srv/dcluster/shared
      static:
        command:
        - 'slurmctld'
        environment:
          MYSQL_DATABASE: slurm_acct_db
          MYSQL_PASSWORD: password
          MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
          MYSQL_USER: slurm
        expose:
        - '6817'
        - '6819'
    
    template: cluster-extended.yml.j2

