---

networking:
    supernet: '172.30.0.0/16'
    cidr_bits: 24
    prefix: 'dcluster'
    gateway: 'gateway'

prefs:
  ssh_user: 'ci-user'

clusters:
  
  simple:

    template: cluster-simple.yml.j2

    head:
      hostname: 'head'
      image: 'centos7:ssh'

    compute:
      hostname:
          prefix: 'node'
          suffix_len: 3          
      image:  'centos7:ssh'
  
  slurm:

    extend: 'simple'

    head:
      image: 'centos7:slurmctld'
      shared_mounts:
        - '/home:/home'
        - '/opt/intel:/opt/intel'
        - '/srv/shared:/srv/dcluster/shared'
      docker_mounts:
        - 'var_lib_mysql:/var/lib/mysql'
        - 'etc_munge:/etc/munge'
        - 'etc_slurm:/etc/slurm'
        - 'slurm_jobdir:/data'
        - 'var_log_slurm:/var/log/slurm'
      static:
        environment:
          MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
          MYSQL_DATABASE: 'slurm_acct_db'
          MYSQL_USER: 'slurm'
          MYSQL_PASSWORD: 'password'
        expose:
            - '6817'
            - '6819'

    compute:
      image: 'centos7:slurm'
      shared_mounts:
        - '/home:/home'
        - '/opt/intel:/opt/intel'
        - '/srv/shared:/srv/dcluster/shared'
      docker_mounts:
        - 'etc_munge:/etc/munge'
        - 'etc_slurm:/etc/slurm'
        - 'slurm_jobdir:/data'
        - 'var_log_slurm:/var/log/slurm'
      static:
        expose:
            - '6818'
        shm_size: 4g
