---

networking:
    supernet: '172.30.0.0/16'
    cidr_bits: 24
    prefix: 'dcluster'

naming:
    head_name: 'head'
    gateway_name: 'gateway'
    compute_prefix: 'node'
    compute_suffix_len: 3

prefs:
  ssh_user: 'ci-user'
