---

paths:
  templates: 'templates'
  bootstrap: '$PWD/bootstrap'
  work: $PWD/.dcluster
  ansible_static: 'ansible_static'
  flavors:
    - config/flavors
    - ~/.dcluster/flavors

prefs:
  hostname_alias:
    enabled: True
    suffix: ice1-1
  log_level: DEBUG
