---

paths:
  templates: 'templates'
  bootstrap: '$PWD/bootstrap'
  work: $PWD/.dcluster
  ansible_static: 'ansible_static'
  profiles:
    - config/profiles
    - ~/.dcluster/profiles

prefs:
  hostname_alias:
    enabled: True
    suffix: ice1-1
  log_level: DEBUG
