---

paths:
  templates: '/usr/share/dcluster/templates'
  bootstrap: '/usr/share/dcluster/bootstrap'
  work: $HOME/.dcluster
  ansible_static: '/usr/share/dcluster/ansible_static'
  profiles:
    - /usr/share/dcluster/profiles
    - ~/.dcluster/profiles

prefs:
  log_level: INFO
  hostname_alias:
    enabled: False
    suffix:
