---

paths:
  templates: '/usr/share/dcluster/templates'
  bootstrap: '/usr/share/dcluster/bootstrap'
  work: $HOME/.dcluster
  ansible_static: '/usr/share/dcluster/ansible_static'
  flavors:
    - /usr/share/dcluster/flavors
    - ~/.dcluster/flavors

prefs:
  log_level: INFO
