#!/bin/bash

#
# Reproduce the functionality of dcluster-ansible command within development environment.
# Should use development configuration.
#
# Giacomo Mc Evoy <giacomo.valenzano@atos.net>
# Atos 2019
#

# calculate directory local to script
SCRIPTS_DIR="$( cd "$( dirname "$0" )" && pwd )"
SRC_HOME_DIR=$SCRIPTS_DIR/..

PYTHON=$(${SCRIPTS_DIR}/find-python.sh)

# call dcluster.dansible.main
DCLUSTER_DEV=True PYTHONPATH=$SRC_HOME_DIR $PYTHON -m dcluster.dansible.main $@
