#!/bin/bash

#
# Reproduce the functionality of dcluster command within development environment.
# Should use development configuration.
#
# Giacomo Mc Evoy <giacomo.valenzano@atos.net>
# Atos 2019
#

# calculate directory local to script
SCRIPTS_DIR="$( cd "$( dirname "$0" )" && pwd )"
SRC_HOME_DIR=$SCRIPTS_DIR/..

PYTHON=$(${SCRIPTS_DIR}/find-python.sh)

# add downloadable programs to PATH
export PATH=$HOME/.dcluster/bin:$PATH

# call dcluster.main, let bash decide which python to use
DCLUSTER_DEV=True PYTHONPATH=$SRC_HOME_DIR $PYTHON -m dcluster.main $@
