#!/bin/bash -x

#
# Reproduce the functionality of dcluster-ansible command within development environment.
# Should use development configuration.
#
# Giacomo Mc Evoy <giacomo.valenzano@atos.net>
# Atos 2019
#

# calculate directory local to script
SCRIPTS_DIR="$( cd "$( dirname "$0" )" && pwd )"
SRC_HOME_DIR=$SCRIPTS_DIR/..

# call dcluster.dansible.main, let bash decide which python to use
DCLUSTER_DEV=True PYTHONPATH=$SRC_HOME_DIR python -m dcluster.dansible.main $@
